# Generated by Django 6.0.2 on 2026-02-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=20)),
                ('document_id', models.CharField(max_length=50)),
                ('role_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_date', models.DateField()),
                ('action_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('cost_center_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cost_center_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseAccount',
            fields=[
                ('account_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=150)),
                ('item_group', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=20, null=True)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('entity_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=150)),
                ('vendor_group', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], max_length=20)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_month', models.IntegerField()),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_core.category')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.costcenter')),
            ],
        ),
        migrations.AddField(
            model_name='costcenter',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='erp_core.department'),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_date', models.DateField()),
                ('reference_type', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.item')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='erp_core.legalentity'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('created_date', models.DateField()),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Received', 'Received'), ('Invoiced', 'Invoiced')], max_length=20)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='erp_core.costcenter')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='erp_core.department')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='erp_core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('receipt_status', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=20, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.item')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp_core.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('receipt_date', models.DateField()),
                ('delivery_delay_days', models.IntegerField(blank=True, null=True)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.purchaseorderline')),
            ],
        ),
        migrations.CreateModel(
            name='GLPosting',
            fields=[
                ('gl_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.expenseaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_core.category')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.costcenter')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.department')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='erp_core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=30)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_core.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryOnHand',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse', models.CharField(max_length=50)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.item')),
            ],
            options={
                'unique_together': {('item', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='ItemVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='erp_core.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_core.vendor')),
            ],
            options={
                'unique_together': {('item', 'vendor')},
            },
        ),
    ]
